export const UI_EXERCISES_LIST_LOADING = 'UI_EXERCISES_LIST_LOADING'

export const UI_EXERCISE_HISTORY_LOADING = 'UI_EXERCISE_HISTORY_LOADING'

export const UI_EXERCISE_EDITOR_LOADING = 'UI_EXERCISE_EDITOR_LOADING'

export const UI_EXERCISE_HISTORY_INFO = 'UI_EXERCISE_HISTORY_INFO'
